// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://joistjaftokyvlkwpdlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvaXN0amFmdG9reXZsa3dwZGx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NzMzNDksImV4cCI6MjA1ODE0OTM0OX0.JA05i3mNcgPatwiVFK5b2mmVH38pjA9XfcUZFdi-hVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);